// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using saharacomnew.Data;

#nullable disable

namespace saharacomnew.Migrations
{
    [DbContext(typeof(SaharaDbContext))]
    [Migration("20220615160845_inital")]
    partial class inital
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("saharacomnew.Models.Article", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("designation")
                        .HasColumnType("longtext");

                    b.Property<string>("info")
                        .HasColumnType("longtext");

                    b.Property<double>("prixachatHt")
                        .HasColumnType("double");

                    b.Property<double>("prixachatttc")
                        .HasColumnType("double");

                    b.Property<double>("prixventeHt")
                        .HasColumnType("double");

                    b.Property<double>("prixventettc")
                        .HasColumnType("double");

                    b.Property<int>("qteacheté")
                        .HasColumnType("int");

                    b.Property<int>("qtevendue")
                        .HasColumnType("int");

                    b.Property<string>("refence")
                        .HasColumnType("longtext");

                    b.Property<int>("stockfinal")
                        .HasColumnType("int");

                    b.Property<int>("stockinitial")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("saharacomnew.Models.Client", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("adresse")
                        .HasColumnType("longtext");

                    b.Property<string>("code")
                        .HasColumnType("longtext");

                    b.Property<string>("nom")
                        .HasColumnType("longtext");

                    b.Property<string>("numphone")
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("saharacomnew.Models.DetailLivraison", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Articleid")
                        .HasColumnType("int");

                    b.Property<int>("Livraisonid")
                        .HasColumnType("int");

                    b.Property<double>("Montantht")
                        .HasColumnType("double");

                    b.Property<int>("Tvaid")
                        .HasColumnType("int");

                    b.Property<double>("montantttc")
                        .HasColumnType("double");

                    b.Property<int>("num")
                        .HasColumnType("int");

                    b.Property<double>("prixht")
                        .HasColumnType("double");

                    b.Property<double>("prixttc")
                        .HasColumnType("double");

                    b.Property<int>("qteup")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("Articleid");

                    b.HasIndex("Livraisonid");

                    b.HasIndex("Tvaid");

                    b.ToTable("DetailLivraisons");
                });

            modelBuilder.Entity("saharacomnew.Models.Livraison", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("Montantht")
                        .HasColumnType("double");

                    b.Property<int>("clientid")
                        .HasColumnType("int");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("info")
                        .HasColumnType("longtext");

                    b.Property<double>("montantttc")
                        .HasColumnType("double");

                    b.Property<int>("num")
                        .HasColumnType("int");

                    b.Property<int>("tva")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("clientid");

                    b.ToTable("Livraisons");
                });

            modelBuilder.Entity("saharacomnew.Models.Tva", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("code")
                        .HasColumnType("longtext");

                    b.Property<string>("designation")
                        .HasColumnType("longtext");

                    b.Property<int>("taux")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Tvas");
                });

            modelBuilder.Entity("saharacomnew.Models.DetailLivraison", b =>
                {
                    b.HasOne("saharacomnew.Models.Article", "Articles")
                        .WithMany()
                        .HasForeignKey("Articleid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("saharacomnew.Models.Livraison", "Livraisons")
                        .WithMany()
                        .HasForeignKey("Livraisonid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("saharacomnew.Models.Tva", "Tvas")
                        .WithMany()
                        .HasForeignKey("Tvaid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Articles");

                    b.Navigation("Livraisons");

                    b.Navigation("Tvas");
                });

            modelBuilder.Entity("saharacomnew.Models.Livraison", b =>
                {
                    b.HasOne("saharacomnew.Models.Client", "Clients")
                        .WithMany()
                        .HasForeignKey("clientid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clients");
                });
#pragma warning restore 612, 618
        }
    }
}
